# Classificação binaria

Quando a 2 classes para fazer a previsão

In [7]:
import pandas as pd

In [21]:
pd.__version__

'2.2.2'

Atributos previsores:

Usar caminho absoluto do arquivo e colocar o r'Caminho do arquivo' para não dar problema com a '\'

In [33]:
X = pd.read_csv(r'C:\Users\thier\Jupyter\Card-12\Seção 4\entradas_breast.csv')
X

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

Carregar a classe:

In [43]:
y = pd.read_csv(r'C:\Users\thier\Jupyter\Card-12\Seção 4\saidas_breast.csv')
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

Dividir os dados em treinamento e teste

In [45]:
import sklearn
from sklearn.model_selection import train_test_split

In [48]:
sklearn.__version__

'1.4.2'

test_size=0.25 -> 25% dos dados serão para teste

In [52]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.25)

Quantidade de dados para treinamento:

In [61]:
X_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

Quantidade de dados para Treinamento:

In [63]:
X_teste.shape, y_teste.shape

((143, 30), (143, 1))

Estrutura da rede neural

In [68]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [70]:
tf.__version__

'2.17.0'

In [74]:
(30 + 1)/ 2

15.5

In [117]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape = (30,)), #30 neuronios na camada de entrada
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'), #16 neuronios na camada oculta, função de ativação relu e inicialização dos pesos
    tf.keras.layers.Dense(units = 16, activation = 'relu', kernel_initializer = 'random_uniform'), #Mais 1 camada oculta
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid') #Camada de saída
])

In [119]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

Configurando Parametros:

In [121]:
otimizador = tf.keras.optimizers.Adam(learning_rate = 0.001, clipvalue = 0.5)

In [123]:
rede_neural.compile(optimizer = otimizador, loss = 'binary_crossentropy', metrics = ['binary_accuracy']) #algoritmo para ajuste dos pesos, função que fara o calculo dos erros, lista com as metricas retornadas

Treinando a rede neural

In [125]:
rede_neural.fit(X_treinamento, y_treinamento, batch_size = 10, epochs = 100)

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - binary_accuracy: 0.5247 - loss: 1.5516
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.6799 - loss: 0.5899 
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.7467 - loss: 0.4649
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.7640 - loss: 0.4750 
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8173 - loss: 0.4185 
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8023 - loss: 0.4164 
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8178 - loss: 0.4887
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8524 - loss: 0.4031
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8504 - loss: 0.4072
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.8300 - loss: 0.4222
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - binary_accuracy: 0.85

In [133]:
len(pesos0)

2

Visualizando os pesos:

In [131]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[-1.88278295e-02, -1.67131834e-02,  6.17245995e-02,
          1.44009396e-01, -2.72264212e-01,  1.33758157e-01,
         -2.19600089e-02, -4.41139877e-01,  7.92338792e-03,
         -2.16831550e-01, -2.38531098e-01, -1.58787481e-02,
         -3.03398490e-01, -2.42784888e-01, -8.46646652e-02,
          3.01566571e-02],
        [ 6.03218079e-02,  2.09388137e-02, -3.15584280e-02,
          6.90600649e-02, -3.12190354e-01,  1.05647258e-01,
          9.12154838e-03, -4.94440705e-01, -8.99229646e-02,
         -2.37513602e-01, -1.26268685e-01,  1.08294174e-01,
         -2.16117129e-01, -2.44312167e-01, -1.20719455e-01,
          1.12120561e-01],
        [-3.16418111e-02,  3.50257754e-02, -5.01523018e-02,
          7.50813931e-02, -1.02480114e-01, -2.86140572e-02,
         -4.34997305e-02, -1.93427965e-01,  3.72999050e-02,
          9.21222791e-02, -1.01581417e-01,  9.50177535e-02,
         -3.40588577e-02, -7.05011413e-02, -9.88993645e-02,
         -8.69954452e-02],
        [ 8.9930586

In [141]:
len(pesos0)

2

Pesos das baias:

In [147]:
pesos0[1]

array([-0.43433532,  0.33492514, -0.03136262,  0.22037457,  0.12674741,
       -0.1998794 , -0.00990649, -0.10444452,  0.34278104,  0.2282489 ,
        0.21852916,  0.11968071,  0.10565764,  0.17564505, -0.3571114 ,
       -0.27432367], dtype=float32)

In [137]:
len(pesos0[1])

16

In [143]:
len(pesos0[0])

30

In [145]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[-3.16138491e-02, -4.59125713e-02, -3.89194079e-02,
         -5.48292175e-02, -2.22956575e-03, -2.09464300e-02,
         -2.06274968e-02,  2.19884321e-01,  1.20976205e-04,
          1.98218767e-02, -5.76810502e-02,  7.59571046e-02,
         -1.71404984e-02, -5.26507907e-02, -1.52104450e-02,
          3.34432386e-02],
        [-7.67915472e-02,  1.01759145e-02, -2.65832655e-02,
          1.15012541e-01,  9.79955420e-02, -1.46450818e-01,
          1.06238043e-02, -1.63508579e-01,  1.12075042e-02,
         -5.42127863e-02, -3.24111544e-02,  3.12923566e-02,
          5.68364076e-02, -1.29858395e-02, -1.98953941e-01,
         -3.97319831e-02],
        [ 6.10322878e-03,  2.87363306e-02, -3.17050293e-02,
         -1.90151390e-02, -6.06200732e-02, -1.81395840e-02,
          2.98536196e-02, -8.47982243e-02, -5.30741131e-03,
         -1.02936402e-01, -3.79550084e-02,  3.66945821e-03,
          1.22425314e-02,  2.01126579e-02,  1.41810656e-01,
         -7.78489187e-02],
        [-3.7867020

Previsão com rede neural:

16 neurônios da camada oculta ligados com 1 neurônio da camada de saída 

In [150]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[ 0.01887152],
        [-0.5192679 ],
        [-0.21223456],
        [-0.5014235 ],
        [ 0.2105103 ],
        [-0.25786224],
        [-0.06365436],
        [ 0.09068339],
        [ 0.4093166 ],
        [-0.7433038 ],
        [-0.31067544],
        [-0.42010337],
        [-0.75648534],
        [-0.20997217],
        [ 0.10664141],
        [ 0.19132279]], dtype=float32),
 array([0.2885902], dtype=float32)]

In [101]:
previsoes = rede_neural.predict(X_teste)
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


In [103]:
previsoes

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [

In [105]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [107]:
accuracy_score(y_teste, previsoes)

0.8601398601398601

In [109]:
confusion_matrix(y_teste, previsoes)

array([[51,  7],
       [13, 72]], dtype=int64)

In [111]:
48 + 80, 9 + 6

(128, 15)

Acertou 128 registros e errou 15

In [127]:
rede_neural.evaluate(X_teste, y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binary_accuracy: 0.6875 - loss: 1.1011  


[1.214367151260376, 0.6783216595649719]

valor do erro, acerto 